packages:
  - apps/*
  - packages/*
overrides:
  braces@<2.3.1: '>=2.3.1'
  postcss@<8.4.31: '>=8.4.31'
  nth-check@<2.0.1: '>=2.0.1'
  braces@<3.0.3: '>=3.0.3'
  micromatch@<4.0.8: '>=4.0.8'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
