/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Recipes API
 * The recipes API description
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TagNamesEntity
} from '.././model';

import { customInstance } from '.././custom-instance';
import type { ErrorType } from '.././custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const tagsControllerTagNameListV1 = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TagNamesEntity>(
      {url: `/v1/tag-names`, method: 'GET', signal
    },
      options);
    }
  

export const getTagsControllerTagNameListV1QueryKey = () => {
    return [`/v1/tag-names`] as const;
    }

    
export const getTagsControllerTagNameListV1QueryOptions = <TData = Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTagsControllerTagNameListV1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tagsControllerTagNameListV1>>> = ({ signal }) => tagsControllerTagNameListV1(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TagsControllerTagNameListV1QueryResult = NonNullable<Awaited<ReturnType<typeof tagsControllerTagNameListV1>>>
export type TagsControllerTagNameListV1QueryError = ErrorType<unknown>


export function useTagsControllerTagNameListV1<TData = Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tagsControllerTagNameListV1>>,
          TError,
          Awaited<ReturnType<typeof tagsControllerTagNameListV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTagsControllerTagNameListV1<TData = Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tagsControllerTagNameListV1>>,
          TError,
          Awaited<ReturnType<typeof tagsControllerTagNameListV1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTagsControllerTagNameListV1<TData = Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTagsControllerTagNameListV1<TData = Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tagsControllerTagNameListV1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTagsControllerTagNameListV1QueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



